import { escapeStringRegexp } from "next/dist/shared/lib/escape-regexp";

export const YALE_TO_HANGUL_INITIAL_CONSONANTS: Record<string, string> = {
  k: "ᄀ",
  kk: "ᄁ",
  n: "ᄂ",
  nn: "ᄔ",
  t: "ᄃ",
  tt: "ᄄ",
  l: "ᄅ",
  m: "ᄆ",
  p: "ᄇ",
  pp: "ᄈ",
  s: "ᄉ",
  ss: "ᄊ",
  G: "ᄋ",
  GG: "ᅇ",
  c: "ᄌ",
  cc: "ᄍ",
  ch: "ᄎ",
  kh: "ᄏ",
  th: "ᄐ",
  ph: "ᄑ",
  h: "ᄒ",

  pk: "ᄞ",
  pt: "ᄠ",
  ps: "ᄡ",
  psk: "ᄢ",
  pst: "ᄣ",
  psc: "ᄦ",
  pc: "ᄧ",
  pth: "ᄩ",
  W: "ᄫ",
  sk: "ᄭ",
  skh: "ᄸ",
  sn: "ᄮ",
  sm: "ᄱ",
  st: "ᄯ",
  sth: "ᄹ",
  sp: "ᄲ",
  sph: "ᄺ",
  spk: "ᄳ",
  sss: "ᄴ",
  sG: "ᄵ",
  sc: "ᄶ",
  sch: "ᄷ",
  sh: "ᄻ",
  z: "ᅀ",
  hh: "ᅘ",
  q: "ᅙ",

  ng: "ᅌ",

  "s/": "ᄼ",
  "ss/": "ᄽ",
  "c/": "ᅎ",
  "cc/": "ᅏ",
  "ch/": "ᅔ",

  "s\\": "ᄾ",
  "ss\\": "ᄿ",
  "c\\": "ᅐ",
  "cc\\": "ᅑ",
  "ch\\": "ᅕ",

  "`": "ᅟ",
};
export const YALE_TO_HANGUL_FINAL_CONSONANTS: Record<string, string> = {
  k: "ᆨ",
  kk: "ᆩ",
  ks: "ᆪ",
  n: "ᆫ",
  nc: "ᆬ",
  nk: "ᇅ",
  nt: "ᇆ",
  ns: "ᇇ",
  nz: "ᇈ",
  nh: "ᆭ",
  t: "ᆮ",
  l: "ᆯ",
  lk: "ᆰ",
  lks: "ᇌ",
  lt: "ᇎ",
  lm: "ᆱ",
  lmk: "ᇑ",
  lms: "ᇒ",
  lmh: "ퟘ",
  lp: "ᆲ",
  lps: "ᇓ",
  ls: "ᆳ",
  lss: "ᇖ",
  lth: "ᆴ",
  lph: "ᆵ",
  lh: "ᆶ",
  lz: "ᇗ",
  lW: "ᇕ",
  lq: "ᇙ",
  m: "ᆷ",
  p: "ᆸ",
  ps: "ᆹ",
  s: "ᆺ",
  ss: "ᆻ",
  G: "ᆼ",
  c: "ᆽ",
  ch: "ᆾ",
  kh: "ᆿ",
  th: "ᇀ",
  ph: "ᇁ",
  h: "ᇂ",
  nth: "ᇉ",
  nch: "ퟌ",
  mk: "ᇚ",
  mp: "ᇜ",
  ms: "ᇝ",
  mz: "ᇟ",
  mch: "ᇠ",
  M: "ᇢ",
  W: "ᇦ",
  sk: "ᇧ",
  st: "ᇨ",
  z: "ᇫ",
  ng: "ᇰ",
  ngk: "ᇬ",
  ngkk: "ᇭ",
  ngkh: "ᇯ",
  f: "ᇴ",
  q: "ᇹ",
  ngs: "ᇱ",
  pl: "ᇣ",
};
export const YALE_TO_HANGUL_CONSONANTS: Record<string, string> = {
  ...YALE_TO_HANGUL_FINAL_CONSONANTS,
  ...YALE_TO_HANGUL_INITIAL_CONSONANTS,
};
export const YALE_TO_HANGUL_VOWELS: Record<string, string> = {
  a: "ᅡ",
  ay: "ᅢ",
  ya: "ᅣ",
  yay: "ᅤ",
  e: "ᅥ",
  ey: "ᅦ",
  ye: "ᅧ",
  yey: "ᅨ",
  wo: "ᅩ",
  wa: "ᅪ",
  way: "ᅫ",
  woy: "ᅬ",
  yo: "ᅭ",
  wu: "ᅮ",
  we: "ᅯ",
  wey: "ᅰ",
  wuy: "ᅱ",
  yu: "ᅲ",
  u: "ᅳ",
  uy: "ᅴ",
  i: "ᅵ",

  o: "ᆞ",
  oy: "ᆡ",
  yoy: "ᆈ",
  yuy: "ᆔ",
  ywe: "ᆑ",
  ywey: "ᆒ",
  ywa: "ᆄ",
  yway: "ᆅ",
};
export const YALE_TO_HANGUL_TONE_MARKS: Record<string, string> = {
  L: "",
  H: "〮",
  R: "〯",
};
// prettier-ignore
const TO_COMPATIBLITY_CONS: Record<string, string> = {
  "ᄀ": "ㄱ",
  "ᄁ": "ㄲ",
  "ᆪ": "ㄳ",
  "ᄂ": "ㄴ",
  "ᆬ": "ㄵ",
  "ᆭ": "ㄶ",
  "ᄃ": "ㄷ",
  "ᄄ": "ㄸ",
  "ᄅ": "ㄹ",
  "ᆰ": "ㄺ",
  "ᆱ": "ㄻ",
  "ᆲ": "ㄼ",
  "ᆳ": "ㄽ",
  "ᆴ": "ㄾ",
  "ᆵ": "ㄿ",
  "ᄚ": "ㅀ",
  "ᄆ": "ㅁ",
  "ᄇ": "ㅂ",
  "ᄈ": "ㅃ",
  "ᄡ": "ㅄ",
  "ᄉ": "ㅅ",
  "ᄊ": "ㅆ",
  "ᄋ": "ㅇ",
  "ᄌ": "ㅈ",
  "ᄍ": "ㅉ",
  "ᄎ": "ㅊ",
  "ᄏ": "ㅋ",
  "ᄐ": "ㅌ",
  "ᄑ": "ㅍ",
  "ᄒ": "ㅎ",
  "ᄔ": "ㅥ",
  "ᄕ": "ㅦ",
  "ᇇ": "ㅧ",
  "ᇈ": "ㅨ",
  "ᇌ": "ㅩ",
  "ᇎ": "ㅪ",
  "ᇓ": "ㅫ",
  "ᇗ": "ㅬ",
  "ᇙ": "ㅭ",
  "ᄜ": "ㅮ",
  "ᇝ": "ㅯ",
  "ᇟ": "ㅰ",
  "ᄝ": "ㅱ",
  "ᄞ": "ㅲ",
  "ᄠ": "ㅳ",
  "ᄢ": "ㅴ",
  "ᄣ": "ㅵ",
  "ᄧ": "ㅶ",
  "ᄩ": "ㅷ",
  "ᄫ": "ㅸ",
  "ᄬ": "ㅹ",
  "ᄭ": "ㅺ",
  "ᄮ": "ㅻ",
  "ᄯ": "ㅼ",
  "ᄲ": "ㅽ",
  "ᄶ": "ㅾ",
  "ᅀ": "ㅿ",
  "ᅇ": "ㆀ",
  "ᅌ": "ㆁ",
  "ᇱ": "ㆂ",
  "ᇲ": "ㆃ",
  "ᅗ": "ㆄ",
  "ᅘ": "ㆅ",
  "ᅙ": "ㆆ",
};
// prettier-ignore
const TO_COMPATIBILITY_VOWELS: Record<string, string> = {
  "ᅡ": "ㅏ",
  "ᅢ": "ㅐ",
  "ᅣ": "ㅑ",
  "ᅤ": "ㅒ",
  "ᅥ": "ㅓ",
  "ᅦ": "ㅔ",
  "ᅧ": "ㅕ",
  "ᅨ": "ㅖ",
  "ᅩ": "ㅗ",
  "ᅪ": "ㅘ",
  "ᅫ": "ㅙ",
  "ᅬ": "ㅚ",
  "ᅭ": "ㅛ",
  "ᅮ": "ㅜ",
  "ᅯ": "ㅝ",
  "ᅰ": "ㅞ",
  "ᅱ": "ㅟ",
  "ᅲ": "ㅠ",
  "ᅳ": "ㅡ",
  "ᅴ": "ㅢ",
  "ᅵ": "ㅣ",
  "ᆄ": "ㆇ",
  "ᆅ": "ㆈ",
  "ᆈ": "ㆉ",
  "ᆑ": "ㆊ",
  "ᆒ": "ㆋ",
  "ᆔ": "ㆌ",
  "ᆞ": "ㆍ",
  "ᆡ": "ㆎ",
};
export const TO_COMPATIBILITY_FORM: Record<string, string> = {
  ...TO_COMPATIBLITY_CONS,
  ...TO_COMPATIBILITY_VOWELS,
};

function inv(obj: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(obj).map(([k, v]) => [v, k]));
}

export const HANGUL_TO_YALE: Record<string, string> = {
  ...inv(YALE_TO_HANGUL_INITIAL_CONSONANTS),
  ...inv(YALE_TO_HANGUL_VOWELS),
  ...inv(YALE_TO_HANGUL_FINAL_CONSONANTS),
  "〮": "H",
  "〯": "R",
};
export const INITIAL_HANGUL_TO_YALE: Record<string, string> = {
  ...inv(YALE_TO_HANGUL_INITIAL_CONSONANTS),
};
export const VOWEL_HANGUL_TO_YALE: Record<string, string> = {
  ...inv(YALE_TO_HANGUL_VOWELS),
};

function makeRegex(items: string[], maxLen: number): RegExp {
  const sortedItems: string[] = [];
  for (let len = maxLen; len > 0; --len) {
    for (const item of items) {
      if (item.length === len) {
        sortedItems.push(escapeStringRegexp(item));
      }
    }
  }
  return new RegExp(`(${sortedItems.join("|")})`);
}
export const VOWELS_RE = makeRegex(Object.keys(YALE_TO_HANGUL_VOWELS), 4);
export const CONS_RE = makeRegex(
  Array.from(
    new Set([
      ...Object.keys(YALE_TO_HANGUL_INITIAL_CONSONANTS),
      ...Object.keys(YALE_TO_HANGUL_FINAL_CONSONANTS),
    ]),
  ),
  4,
);

export const INDEP_CONS_RE =
  /([ᄀᄁᄂᄔᄃᄄᄅᄆᄇᄈᄉᄊᄋᅇᄌᄍᄎᄏᄐᄑᄒᄞᄠᄡᄢᄣᄦᄧᄩᄫᄭᄮᄯᄲᄶᄻᅀᅘᅙᅌᄼᄽᅎᅏᅔᄾᄿᅐᅑᅕᅟ])(?![ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵᆞᆡᆈᆔᆑᆒᆄᆅ])/;
export const COMPAT_VOWELS_RE =
  /[ㅏㅐㅑㅒㅓㅔㅕㅖㅗㅘㅙㅚㅛㅜㅝㅞㅟㅠㅡㅢㅣㆇㆈㆉㆊㆋㆌㆍㆎ]/;
